---  
- name: Install basic dev packages
  yum:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
    - gcc
    - kernel-devel 
    - kernel-headers 
    - dkms 
    - make 
    - cmake3
    - bzip2 
    - perl 
    - git
    - openssl-devel
    - zip
    - unzip

- include: ninja.yml

- name: Install Software Collections
  yum:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
    - yum-conf-repos
    - yum-conf-softwarecollections

- name: Install dev toolset 6
  yum:
    name: devtoolset-6
    state: present
  become: true