---
- name: Check is ninja installed with stat
  stat:
    path: /usr/local/bin/ninja
  register: ninja_stat_result

- name: Download ninja
  get_url:
    url: https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
    dest: /tmp/
    validate_certs: false
  become: true
  when: ninja_stat_result.stat.exists == False

- name: Extract ninja
  unarchive:
    src: /tmp/ninja-linux.zip
    dest: /usr/local/bin/
  become: true
  when: ninja_stat_result.stat.exists == False